import 'package:flutter/material.dart';

Map<String, List<Color>> fiberColors = {
  'DIN/VDE 08888': [
    Colors.red,
    Colors.green,
    Colors.blue,
    Colors.yellow,
    Colors.white,
    Colors.grey,
    Colors.brown,
    Colors.purple,
    Colors.cyanAccent,
    Colors.black,
    Colors.orange,
    Colors.pink[200]!,
    Colors.red,
    Colors.green,
    Colors.blue,
    Colors.yellow,
    Colors.white,
    Colors.grey,
    Colors.brown,
    Colors.purple,
    Colors.cyanAccent,
    Colors.black,
    Colors.orange,
    Colors.pink[200]!],
  'SNR': [
    Colors.grey[100]!,
    Colors.red,
    Colors.blue,
    Colors.green,
    Colors.yellow,
    Colors.purple,
    Colors.orange,
    Colors.brown,
    Colors.cyanAccent,
    Colors.pink[200]!,
    Colors.grey,
    Colors.black,
    Colors.grey[100]!,
    Colors.red,
    Colors.blue,
    Colors.green,
    Colors.yellow,
    Colors.purple,
    Colors.orange,
    Colors.brown,
    Colors.cyanAccent,
    Colors.pink[200]!,
    Colors.grey,
    Colors.black,
  ]
};
